config/routes.rb
Rails.application.routes.draw do
  root 'todos#index'

  resources :todos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
    def index
        @todos = Todo.all
    end

    def show
        @todo = Todo.find(params[:id])
    end

    def new
        @todo = Todo.new
    end

    def create
        @todo = Todo.create todo_params
        redirect_to todo_path(@todo)
    end

    def edit
        @todo = Todo.find(params[:id])
    end

    def update
        @todo = Todo.find(params[:id])
        @todo.update todo_params
        redirect_to todo_path(@todo)
    end

    def destroy
        Todo.find(params[:id]).destroy
        redirect_to root_path
    end

    private
    def todo_params
      params.require(:todo).permit(:title, :description)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/edit.html.erb
<h1>Edit Your Todo</h1>
<%= form_for @todo do |f| %>

  <%= label_tag(:title, "Title:") %>
  <%= f.text_field :title %></br>

  <%= label_tag(:description, "Description") %>
  <%= f.text_area :description %></br>

  <%= f.submit "Update" %>
<% end %>

app/views/todos/index.html.erb
<h1> Index Page! </h1>

<%= link_to "New Todo Item", new_todo_path %>

<% @todos.each do |todo| %>
    <li>
      <%= link_to todo.title, todo_path(todo.id) %>
      <%= link_to "edit", edit_todo_path(todo[:id]) %>
      <%= link_to "delete", todo, method: :delete, data: { confirm: "You sure?" }%>
    </li>
<% end %>

app/views/todos/new.html.erb
<h1>Create a New Todo</h1>
<%= form_for @todo do |f| %>

  <%= label_tag(:title, "Title:") %>
  <%= f.text_field :title %></br>

  <%= label_tag(:description, "Description") %> 
  <%= f.text_area :description %></br>
  <%= f.submit "Create" %>
<% end %>

app/views/todos/show.html.erb
<h1>Todo Show Page</h1>
<p>Title: <%= @todo['title']%></p>
<p>Description: <%= @todo['description']%></p>

<%= link_to "Back To Todo List",todos_path%>

app/views/welcome/index.html.erb
<p>You're on Rails!</p>